#ifndef GUI_SCROLL_H_INCLUDED
#define GUI_SCROLL_H_INCLUDED

#include <functional>
#include "GuiComposite.h"
#include "GuiScrollBar.h"

namespace Amju
{
class GuiScroll : public GuiComposite
{
public:
  static const char* NAME;

  virtual bool Load(File*); 
  virtual void Draw();
  virtual void Update();

  void Reset(); // Reset offset position and vel

  // Scroll events: could be generated by a scroll bar, keyboard, etc.
  // TODO Make scroll events a type of Event ??
  void OnScrollVelEvent(const Vec2f& scrollVel);
  void StopScrolling(); // set velocity to zero

  void SetExtents(const Vec2f& extents);
  void SetTabStopSize(const Vec2f& tabStopSize) { m_tabStopSize = tabStopSize; }
  using TabStopCallback = std::function<void(GuiElement* thisScroller, int tabStop)>;
  void SetTabStopCallback(TabStopCallback tscb) { m_tabStopCallback = tscb; }

  virtual bool OnKeyEvent(const KeyEvent&); 
  virtual bool OnCursorEvent(const CursorEvent&);
  virtual bool OnMouseButtonEvent(const MouseButtonEvent&);

  void InitScrollBar();

  static void SetTabStopSoundFilename(const std::string& s) { s_tabStopSoundFilename = s; }

protected:
  void PlayTabStopSound(int tabStopNum) const;

  void UpdateForTabStops();

protected:
  // Offset in x and y
  Vec2f m_scrollPos;
  Vec2f m_scrollVel; 

  // Amount by which we are allowed to scroll in x and y
  // TODO Why not use size?
  Vec2f m_extents;

  bool m_leftDrag = false;

  RCPtr<GuiScrollBar> m_scrollBar;

  // "tab stops" - as scroller passes a multiple of a tab stop, we slow down, and stop if below
  //  the lowest speed. We can also click when we pass a tab stop.
  Vec2f m_tabStopSize;

  static std::string s_tabStopSoundFilename;

  TabStopCallback m_tabStopCallback; // called when we hit a tabstop
  int m_lastTabStop = -1; // keep track of most recent tab stop we hit

  // Used to get (dx, dy), as cursor pos delta isn't reliable.
  Vec2f m_lastCursorPos;
};
}

#endif

