#ifndef GUI_SCROLL_H_INCLUDED
#define GUI_SCROLL_H_INCLUDED

#include <functional>
#include "GuiComposite.h"
#include "GuiScrollBar.h"

namespace Amju
{
class GuiScroll : public GuiComposite
{
public:
  static const char* NAME;

  virtual bool Load(File*); 
  virtual void Draw();
  virtual void Update();

  void Reset(); // Reset offset position and vel

  // Scroll events: could be generated by a scroll bar, keyboard, etc.
  // TODO Make scroll events a type of Event ??
  void OnScrollVelEvent(const Vec2f& scrollVel);
  void StopScrolling(); // set velocity to zero

  // Set range of movement
  void SetExtents(const Vec2f& extents);

  // Set distance between tab stops
  void SetTabStopSize(const Vec2f& tabStopSize) { m_tabStopSize = tabStopSize; }

  // Set callback for when we lock onto a tab stop if required
  using TabStopCallback = std::function<void(GuiElement* thisScroller, int tabStop)>;
  void SetTabStopCallback(TabStopCallback tscb) { m_tabStopCallback = tscb; }

  // Set position at a specific tabstop, i.e. a multiple of tab stop size.
  void SetTabStop(int tabStop);

  virtual bool OnKeyEvent(const KeyEvent&); 
  virtual bool OnCursorEvent(const CursorEvent&);
  virtual bool OnMouseButtonEvent(const MouseButtonEvent&);

  void InitScrollBar();

  static void SetTabStopSoundFilename(const std::string& s) { s_tabStopSoundFilename = s; }

  // Scroll behaviour constants
  void SetScrollVelMultiplier(float);
  void SetCanScrollInX(bool);
  void SetCanScrollInY(bool);
  void SetScrollRect(const Rect&);
  void SetStoppingDistance(float);
  void SetStoppingVel(float);
  void SetSpeedBumpMult(float);
  void SetDeceleration(float);
  void SetMinDeceleration(float);
  void SetMaxScrollVel(float);

  float GetScrollVelMultiplier() const;
  bool CanScrollInX() const;
  bool CanScrollInY() const;

  // Start position of scroll must be in this screen-space rect to register.
  // (Not subject to any transform - just a const rect, in screen space coords.)
  const Rect& GetScrollRect() const;
  float GetStoppingDistance() const;
  float GetStoppingVel() const;
  float GetSpeedBumpMult() const;
  float GetDeceleration() const;
  float GetMinDeceleration() const;
  float GetMaxScrollVel() const;

protected:
  void PlayTabStopSound(int tabStopNum) const;

  void UpdateForTabStops();

protected:
  // Offset in x and y
  Vec2f m_scrollPos;
  Vec2f m_scrollVel; 

  // Amount by which we are allowed to scroll in x and y
  // TODO Why not use size?
  Vec2f m_extents;

  bool m_leftDrag = false;

  RCPtr<GuiScrollBar> m_scrollBar;

  // "tab stops" - as scroller passes a multiple of a tab stop, we slow down, and stop if below
  //  the lowest speed. We can also click when we pass a tab stop.
  Vec2f m_tabStopSize;

  static std::string s_tabStopSoundFilename;

  TabStopCallback m_tabStopCallback; // called when we hit a tabstop
  int m_lastTabStop = -1; // keep track of most recent tab stop we hit

  // Used to get (dx, dy), as cursor pos delta isn't reliable.
  Vec2f m_lastCursorPos;

  float m_scrollVelMultiplier = 10.f;
  bool m_canScrollInX = true;
  bool m_canScrollInY = true;
  Rect m_scrollRect = Rect(-1.f, 1.f, -1.f, 1.f);
  float m_stoppingDistance = 0.01f;
  float m_stoppingVel = 0.2f;
  float m_speedBumpMult = 0.6f;
  float m_deceleration = 0.25f;
  float m_minDeceleration = 0.7f;
  float m_maxScrollVel = 4.f;
};
}

#endif

