#ifndef GUI_SCROLL_H_INCLUDED
#define GUI_SCROLL_H_INCLUDED

#include "GuiComposite.h"
#include "GuiScrollBar.h"

namespace Amju
{
class GuiScroll : public GuiComposite
{
public:
  static const char* NAME;

  virtual bool Load(File*); 
  virtual void Draw();
  virtual void Update();

  void Reset(); // Reset offset position and vel

  // Scroll events: could be generated by a scroll bar, keyboard, etc.
  // TODO Make scroll events a type of Event ??
  void OnScrollVelEvent(const Vec2f& scrollVel);
  void StopScrolling(); // set velocity to zero

  void SetExtents(const Vec2f& extents);

  virtual bool OnKeyEvent(const KeyEvent&); 
  virtual bool OnCursorEvent(const CursorEvent&);
  virtual bool OnMouseButtonEvent(const MouseButtonEvent&);

  void InitScrollBar();

private:
  // Offset in x and y
  Vec2f m_scrollPos;
  Vec2f m_scrollVel; 

  // Amount by which we are allowed to scroll in x and y
  // TODO Why not use size?
  Vec2f m_extents;

  bool m_leftDrag = false;

  RCPtr<GuiScrollBar> m_scrollBar;
};
}

#endif

