MGC_OBJECTS = \
	MgcCont2DPointInPolygon$(DOT_O) \
	MgcCont3DSphere$(DOT_O) \
	MgcDist3DLinLin$(DOT_O) \
	MgcDist3DLinTri$(DOT_O) \
	MgcDist3DVecLin$(DOT_O) \
	MgcDist3DVecTri$(DOT_O) \
	MgcIntr3DLinSphr$(DOT_O) \
	MgcIntr3DTriSphr$(DOT_O) \
	MgcMath$(DOT_O) \
	MgcVector2$(DOT_O) \
	MgcVector3$(DOT_O)

libmgc$(DOT_A): $(MGC_OBJECTS)
	$(BUILDSTATICLIB) $(MGC_OBJECTS)

clean:
	rm *$(DOT_O)

