XML_OBJECTS = \
	XmlParser2$(DOT_O) \
	XmlNodeInterface$(DOT_O) 

libxml$(DOT_A): $(XML_OBJECTS)
	$(BUILDSTATICLIB) $(XML_OBJECTS)

XML_TEST_MAIN = XmlTestMain$(DOT_O)

xmltest$(DOT_EXE): $(XML_TEST_MAIN) $(XML_OBJECTS)
	$(BUILDEXE) $(XML_TEST_MAIN) \
	$(XML_OBJECTS) \
	$(STD_LIBS)

clean:
	rm *.o.*

