OBJECTS = \
	adler32$(DOT_O) \
	compress$(DOT_O) \
	crc32$(DOT_O) \
	deflate$(DOT_O) \
	gzio$(DOT_O) \
	infback$(DOT_O) \
	inffast$(DOT_O) \
	inflate$(DOT_O) \
	inftrees$(DOT_O) \
	minigzip$(DOT_O) \
	trees$(DOT_O) \
	uncompr$(DOT_O) \
	zutil$(DOT_O) 

libz$(DOT_A): $(OBJECTS)
	$(BUILDSTATICLIB) $(OBJECTS)

clean:
	rm *$(DOT_O)


